version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_HOST: localhost
      MYSQL_DATABASE: api_jogos
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_jogos
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV = production
      - DB_HOST = mysql
      - DB_PORT = 3306
      - DB_USER = user
      - DB_PASSWORD = 123456
      - DB_NAME = api_jogos
      - DATABASE_URL = mysql://user:123456@mysql:3307/api_jogos

    depends_on:
      mysql:
        condition: service_healthy

    command: npm run dev

volumes:
  mysql-data:
